=== Controlled by EIP-712 signatures

https://github.com/alembic-tech/nft-minting-contracts/blob/main/contracts/erc1155/ERC1155VoucherMinter.sol[ERC1155VoucherMinter]
is a minter contract expected to work in tandem with almost any ERC1155 contract which implements the
https://github.com/alembic-tech/nft-minting-contracts/blob/main/contracts/erc1155/IERC1155Mintable.sol[IERC1155Mintable]
interface.

NOTE: This minting approach is particularly useful when you have some kind of backends
controlling a wallet allowed to sign `ERC1155VoucherMinter.MintRequest`.

The `IERC1155Mintable` interface is pretty basic and a typical ERC1155 mint function:
[source,solidity]
----
include::../contracts/erc1155/IERC1155Mintable.sol[lines=5..10,indent=0]
----
A sample ERC1155 contract, https://github.com/alembic-tech/nft-minting-contracts/blob/main/contracts/test/ERC1155Test.sol[ERC1155Test] is provided,
based on OpenZeppelin roles, and restricting mints to only contracts having the `MINTER_ROLE`.

https://github.com/alembic-tech/nft-minting-contracts/blob/main/test/ERC1155VoucherMinter.spec.ts[ERC1155VoucherMinter.spec.ts]
contains examples on how to use `ERC1155VoucherMinter`.

From your backend, sign a mint request, using the provided
https://github.com/alembic-tech/nft-minting-contracts/blob/main/test/ERC1155VoucherMinter.spec.ts#L147[getTypedRequest] function.
[source,typescript]
----
include::../test/ERC1155VoucherMinter.spec.ts[tags=backend-task,indent=0]
----

In your dApp, to have the user to send the mint transaction, using Ethers:
[NOTE]
====
Such transactions can be relayed if you want. +
Any wallet can send this transaction.
====
[source,typescript]
----
const { domain, types, request } = await getTypedRequest(minter.address, user.address, tokenId, quantity, nonce)
// TODO: make your backend provide the previously generated `signature`
const tx = await minter.mint({ ...request, signature })
----
