=== Whitelist with Merkle Tree

https://github.com/alembic-tech/nft-minting-contracts/blob/main/contracts/erc721/ERC721MerkleTreeMinter.sol[ERC721MerkleTreeMinter]
is a minter contract expected to work in tandem with almost any ERC721 contract which implements the
https://github.com/alembic-tech/nft-minting-contracts/blob/main/contracts/erc721/IERC721Mintable.sol[IERC721Mintable]
interface.

The `IERC721Mintable` interface is pretty basic and a typical ERC721 mint function:
[source,solidity]
----
include::../contracts/erc721/IERC721Mintable.sol[lines=5,indent=0]
----
A sample ERC721 contract, https://github.com/alembic-tech/nft-minting-contracts/blob/main/contracts/test/ERC721Test.sol[ERC721Test] is provided,
based on OpenZeppelin roles, and restricting mints to only contracts having the `MINTER_ROLE`.

https://github.com/alembic-tech/nft-minting-contracts/blob/main/test/ERC721MerkleTreeMinter.spec.ts[ERC721MerkleTreeMinter.spec.ts]
contains examples on how to use `ERC721MerkleTreeMinter`.

The `ERC721MerkleTreeMinter` contract is initialized with a Merkle Tree root, computed from leaves
having the following structure:
[source,typescript,line-comment=//]
----
include::../test/ERC721MerkleTreeMinter.spec.ts[tag=merkle-tree-leaves,indent=0]
----
<1> Address of the whitelisted user
<2> Maximum quantity of NFTs the whitelisted user is allowed to mint
<3> A nonce allowing to have a user included more than once in the tree if need be

Initialize your Merkle Tree with an array of `LeafSourceObject`:
[source,typescript,line-comment=//]
----
include::../test/ERC721MerkleTreeMinter.spec.ts[tag=merkle-tree-computation-example,indent=0]
----

Then compute the Merkle Tree:

WARNING: You will need to keep track of the merkle proofs for each user address in the exact
same order of your leaves array. +
It is quite common to either embed a JSON file in your dApp or store such data a database and
have your dApp fetch the relevant data for the connected user.

[source,typescript,line-comment=//]
----
include::../test/ERC721MerkleTreeMinter.spec.ts[tag=merkle-tree-computation,indent=0]
----

NOTE: The `deployWhitelistedMinter` and `deployMinterWithLeaves` functions included in the
test suite are handy if you want to do this in your scripts.


Finally here is an example of call to have your user mint his NFTs:
[source,typescript,line-comment=//]
----
include::../test/ERC721MerkleTreeMinter.spec.ts[tag=merkle-tree-mint-example,indent=0]
----
<1> address of the user
<2> quantity to mint
<3> max quantity mintable by that user
<4> the nonce
<5> the merkle tree proofs
<6> purchase price
